id: A7DCBAB33
base_file: f4938.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:21:38.782288
  last_modified_at: 2022-05-30 18:21:38.782295
